language: python
matrix:
  include:
  - python: 2.7
    env: TOXENV=py27
  - python: 3.4
    env: TOXENV=py34
  - python: 3.5
    env: TOXENV=py35
  - python: 3.6
    env: TOXENV=py36
  - python: 3.7
    env: TOXENV=py37
    dist: xenial # required for Python >= 3.7
  - python: pypy
    env: TOXENV=pypy
  - python: pypy3
    env: TOXENV=pypy3
install: pip install tox coveralls && tox --notest
script: tox
after_success: coveralls
deploy:
  provider: pypi
  user: jazzband
  server: https://jazzband.co/projects/contextlib2/upload
  distributions: sdist bdist_wheel
  password:
    secure: lmCsNEmxcYTcdDz1ZdoegDvZxIRFBsjoQoT5O1t9GsYKzEMebPxEMZKRIxWXLIu1HKXSSAnb6foDvK+v61VK1PiGBfn2KMeOr1y7G+gm2sOSXRiWtvnzz7LTWTW6cHdwOz6Un3FNxhTRqrQ4Jz9Nsik0YuA+MOn8bhWvTAxY5iIYRuDoyNpUDBwMOTQchfpjJhID0Zhuvk1gTX5Jrp425FPhTvGgUEefBh48PFN/1qBFmV45X5Y0bZEcd8lRGXxrUFej2Pk54sSVurhIAJLmWE9S9VsnBeRZMCB04jWBSGNrrUF11LK2EtzZ701liZzET6NLztLc9ZXdrpSWWQ07W0QinHo4v1PNA7b5JHEhhqEIHlE/XBDSqQrKWbonBlNXp9YXMtTfF5OFPmc2V33ad1WMnqvo0w76twRigGWQsKwWrtJUG0SrSybQg8YxsyH9DfVhUwQ56WhaBZSL8vTN4L8v+rmv2yyAkgmx6GicCF5lDqZs3NpRrK5jWrZSu6prfkfoZhfLz29em75t6JP8d1Q1a9JqFQJTGCe78cDuOj+KAlcIz43G59iGyE63nBJ7VlezUE2XouQs3G2Uf0+bx8YIH43uMbiNb9ITghqPFJEOjcKcv0B3VSUhaV91co+D5NL0AZ9E4dF5jCTrNmt0X20EVOucpm/KWruujXEoCSY=

  on:
    tags: true
    repo: jazzband/contextlib2
    condition: "$TOXENV = py35" # only release once per test run for a Git tag
